// <auto-generated />
using CRM.WebAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRM.WebAPI.Migrations
{
    [DbContext(typeof(CRMWebAPIContext))]
    [Migration("20190611065855_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CRM.WebAPI.Models.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Avatar");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Otch");

                    b.Property<string>("Phone")
                        .IsRequired();

                    b.Property<string>("Surname")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Clients");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Client");
                });

            modelBuilder.Entity("CRM.WebAPI.Models.Company", b =>
                {
                    b.HasBaseType("CRM.WebAPI.Models.Client");

                    b.Property<string>("CompanyName");

                    b.Property<string>("PersonPosition");

                    b.HasDiscriminator().HasValue("Company");

                    b.HasData(
                        new
                        {
                            ID = 3,
                            Avatar = "./img/man.png",
                            Email = "krasko@ufnc.com",
                            Name = "Иван",
                            Otch = "Дмитриевич",
                            Phone = "+79085547441",
                            Surname = "Красько",
                            CompanyName = "УФНЦ",
                            PersonPosition = "Зам. гендиректора"
                        },
                        new
                        {
                            ID = 4,
                            Avatar = "./img/woman.png",
                            Email = "ivanova_marina@ufnc.com",
                            Name = "Марина",
                            Otch = "Дмитриевна",
                            Phone = "+79085544441",
                            Surname = "Иванова",
                            CompanyName = "БашНефть",
                            PersonPosition = "Замначальника отдела закупок"
                        });
                });

            modelBuilder.Entity("CRM.WebAPI.Models.Person", b =>
                {
                    b.HasBaseType("CRM.WebAPI.Models.Client");

                    b.HasDiscriminator().HasValue("Person");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Avatar = "./img/professor.png",
                            Email = "einstein@email.com",
                            Name = "Альберт",
                            Otch = "Германович",
                            Phone = "+79270000105",
                            Surname = "Эйнштейн"
                        },
                        new
                        {
                            ID = 2,
                            Avatar = "./img/geisha.png",
                            Email = "ivasaki@gmail.com",
                            Name = "Минэко",
                            Phone = "+79870045474",
                            Surname = "Ивасаки"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
